name: Snowpress
shortName: Snowpress
description: Documentation site theme
github: https://github.com/ninest/snowpress

navLinks:
  - title: Guide
    url: /guide
  - title: Examples
    url: /examples

footerLinks:
  - title: GitHub
    url: https://github.com/ninest/snowpress

sidebar:
  guide:
    title: Guide
    root: /guide
    sections:
      - links:
          - title: Introduction
            slug: /
          - title: Installation
            slug: /installation

      - title: Navbar
        links:
          - title: Links
            slug: /navbar-links
          - title: GitHub
            slug: /navbar-github

  examples:
    title: Examples
    root: /examples
    sections:
      - links:
          - title: Introduction
            slug: /
          - title: Adding examples
            slug: /adding-examples
