name: Snowy
shortName: Snowy
description: Documentation site theme

navLinks:
  - title: Guide
    url: /guide
  - title: Examples
    url: /examples

footerLinks:
  - title: GitHub
    url: https://github.com/ninest/snowy


sidebar:
  
  guide:
    title: Guide
    root: /guide
    sections:
      - links:
          - title: Introduction
            slug: /
          - title: Installation
            slug: /installation

      - title: Sections
        links:
          - title: Adding
            slug: /section-adding
          - title: Editing
            slug: /section-editing

  examples:
    title: Examples
    root: /examples
    sections:
      - links:
          - title: Introduction
            slug: /
          - title: Adding examples
            slug: /adding-examples
      - title: Another
        links:
          - title: Section
            slug: /lolg
          - title: More
            slug: /more
      - title: Yet
        links:
          - title: Blah blah
            slug: /lolg
          - title: Lorem
            slug: /more
          - title: Section
            slug: /lolg
          - title: Hilo
            slug: /more
          - title: Lorem
            slug: /more
          - title: Section
            slug: /lolg
          - title: Hilo
            slug: /more
      - title: Existence
        links:
          - title: Is overrated
            slug: /lolg
          - title: Nope
            slug: /more
          - title: Section
            slug: /lolg
          - title: Yes plus one
            slug: /more
          - title: Lorem
            slug: /more
          - title: Section
            slug: /lolg
          - title: Hilo
            slug: /more
      - title: Choolest
        links:
          - title: Last
            slug: /last
          